[Vehicle]
VehicleType=3

[DMI]
TexturePath=chubbyginger/InnoSig-E531/image/DMI.png
TextureWidth=1024
TextureHeight=1024
TargetFPS=10
; 强制机车信号显示，-1=不强制(使用实际信号)，0=HU,1=U,2=LU,3=L,4=L2,5=L3,6=L4,7=L5,8=H,9=HB,10=UU,11=UUS,12=U2,13=U2S,14=B
ForceCabSignal=-1
